### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by raffidil** [vdloo/kodictl#9]
It seems ` raco pkg install` is not working:

`Linking current directory as a package
The following uninstalled packages are listed as dependencies of kodictl:
   json-rpc-client
Would you like to install these dependencies? [Y/n/a/c/?] 
Resolving "json-rpc-client" via https://download.racket-lang.org/releases/7.2/catalog/
Resolving "json-rpc-client" via https://pkgs.racket-lang.org
Resolving "json-rpc-client" via https://planet-compats.racket-lang.org
raco pkg install: cannot find package on catalogs
  package: json-rpc-client
`

**Comment by matteoraggi** [comment]
Hi, I have exactly the same issue.
